### PR TITLE
Make public "base.object_manager_provider" and "base.object_repository_provider" services

### PR DESCRIPTION
**Pull request by phansys**
|Q            |A     |
|---          |---   |
|Branch       |master|
|Bug fix?     |no    |
|New feature? |no    |
|BC breaks?   |no    |
|Deprecations?|no    |
|Tests pass?  |yes   |
|Fixed tickets|n/a   |
|License      |MIT   |
|Doc PR       |n/a   |

See description at #45.

### CODE REVIEW

**Comment by mmoreram** [comment]
@phansys thanks for this PR.
Why would you make public both services?
If you need any other object_manager or repository, you should use DIC + Factory pattern

**Comment by phansys** [comment]
I think the need is not on my side. This bundle is providing a trait which expects these services to be publicly available:
https://github.com/mmoreram/BaseBundle/blob/1fddb7313d01883cf9efde658a3eefc2bf69ea30/DependencyInjection/BaseContainerAccessor.php#L77-L84
https://github.com/mmoreram/BaseBundle/blob/1fddb7313d01883cf9efde658a3eefc2bf69ea30/DependencyInjection/BaseContainerAccessor.php#L93-L100

Please, let me know if I'm missing something.
Thank you.

**Comment by mmoreram** [comment]
@phansys the new version of BaseBundle drops the support for doctrine, and version 1 is not longer supported. Feel free to fork the repository if you need any fix :)

**Comment by phansys** [comment]
Thank you!

**Pull request closed without merging**
